### ISSUE TITLE
Azure: support getting credentials using aad-pod-identity

### ISSUE THREAD

**Issue by philwinder** [vmware-tanzu/velero-plugin-for-microsoft-azure#12]
Using aad-pod-identity, in combination with azure identities, it is possible for the cloud provider to get credentials without having to pass them in as environmental variables. Instead, the azure api uses the metadata service to query its current identity (provided by aad-pod-identity) and returns the required client for access.

This is very much like how kiam works.

Can we update the Azure cloud provider to provide this authentication method? Has anyone got this to work already with a work around (e.g. having an external pod get credentials and inject them into the velero pod)?

This has already been discussed here (#379) but was closed. This is also related to vmware-tanzu/velero-plugin-for-microsoft-azure#11.

**Comment by ezYakaEagle442** [comment]
Indeed Managed Indentities in GA in AKS since March, it would be great to have Identity support with Velero

I started a snippet but it will not work if not supported in Velero, see #46 :

```sh

echo -e "\""AZURE_TENANT_ID\""=\""$tenantId\"",\n"\
"\""AZURE_SUBSCRIPTION_ID\""=\""$subId\"",\n"\
"\""AZURE_RESOURCE_GROUP\""=\""$rg_name\"",\n"\
"\""AZURE_CLOUD_NAME\""=\""AzurePublicCloud\"",\n"\
"\""useManagedIdentityExtension\""=true\n"
> ./deploy/credentials-velero

cat ./credentials-velero

export IDENTITY_NAME="velero-pod-identity" #  must consist of lower case 

rg_id=$(az group show --name $rg_name --query id)
echo "RG ID : "  $rg_id

az identity create -n $IDENTITY_NAME -g $rg_name
export IDENTITY_CLIENT_ID="$(az identity show -g $rg_name -n $IDENTITY_NAME --query clientId -otsv)"
export IDENTITY_RESOURCE_ID="$(az identity show -g $rg_name -n $IDENTITY_NAME --query id -otsv)"
export IDENTITY_ASSIGNMENT_ID="$(az role assignment create --role Reader --assignee $IDENTITY_CLIENT_ID --scope /subscriptions/$subId/resourceGroups/$rg_name --query id -o tsv)"

export ResourceID=$IDENTITY_RESOURCE_ID
export ClientID=$IDENTITY_CLIENT_ID
envsubst < ./cnf/velero-pod-identity.yaml > deploy/velero-pod-identity.yaml
cat deploy/velero-pod-identity.yaml

k apply -f deploy/velero-pod-identity.yaml -n $target_namespace
k get azureidentity -A
k get azureidentitybindings -A
k get azureassignedidentities -A

# Role Assignment : to be checked
az role assignment create --role "Contributor" --assignee $IDENTITY_CLIENT_ID --scope $rg_id
az role assignment list --assignee $IDENTITY_CLIENT_ID --scope $rg_id

az role assignment create --role "Contributor" --assignee $IDENTITY_CLIENT_ID --scope $aks_node_rg_id
az role assignment list --assignee $IDENTITY_CLIENT_ID --scope $aks_node_rg_id
```

**Comment by ezYakaEagle442** [comment]
@skriss hi ! could we have an update on Identity support please ?

**Comment by skriss** [comment]
[This PR](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/29) started work on this, but the PR is out-of-date. It'd be great if someone else wanted to pick it up, however it should wait until #43 and #44 get merged to avoid additional conflicts.

**Comment by ezYakaEagle442** [comment]
thanks @skriss #43 & #44 are now marked as merged, so I cross fingers now to get [PR#29](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/29) asap :)

**Comment by skriss** [comment]
see https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/29#issuecomment-637771389

**Comment by krishnadce** [comment]
When is the AAD Podidentity support set to release. I got the following errors when I followed the AAD Podidentity setup and install using helm3.
`An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET`

But AAD Podidentity doesn't require `AZURE_CLIENT_ID, AZURE_CLIENT_SECRET`. 
The plugin version I'm using is velero/velero-plugin-for-microsoft-azure:v1.1.0.
I don't see any release/pre-release after v1.1.0?

**Comment by flomsk** [comment]
Facing the same like @krishnadce 
Do we have to build own docker images while new release will not be deployed ? @skriss

**Comment by skriss** [comment]
You can try it with `velero/velero-plugin-for-microsoft-azure:master` if you're comfortable using a development build of the Azure plugin.

**Comment by ryanmcafee** [comment]
Any idea of when to expect a new docker image to be published that is not master?

**Comment by adamrushuk** [comment]
We're also very keen to get aad-pod-identity working from the next release.

**Comment by skriss** [comment]
cc @vmware-tanzu/velero-maintainers for folks asking about next release date.

**Comment by ashish-amarnath** [comment]
@adamrushuk @ryanmcafee @flomsk @krishnadce 
This change will be in the upcoming release of the plugin, eta end of Aug 2020.
If you would like to use this feature now and you are comfortable you can use `velero/velero-plugin-for-microsoft-azure:main`  which is a development build of the plugin with this feature.

**Comment by lpghartz** [comment]
So... its now October. 

Any ETA on a real release?

**Comment by ashish-amarnath** [comment]
@lpghartz @adamrushuk @Annegies @fgauna12 
Hey folks, we now have a new release with this feature. https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.1.1
Apologies for the delay with this release.
