### ISSUE TITLE
error accessing azure blob at installation 

### ISSUE THREAD

**Issue by katomel4** [vmware-tanzu/velero-plugin-for-microsoft-azure#17]
error accessing azure blob at installation 
velero 1.2.0 plugin 1.0.0
spn as contributor
 
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.0.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID

An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/az%20account%20list%20--query%20%5B%3FisDefault%5D.id%20-o%20tsv/resourceGroups/velerobkrg/providers/Microsoft.Storage/storageAccounts/velero357dcb4c5b0e/listKeys?api-version=2018-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>

**Comment by skriss** [comment]
@katomel4 usually this indicates something in the credentials file is invalid - could you double-check all the values there?

**Comment by katomel4** [comment]
double checked
i will try again with a new cluster

**Comment by skriss** [comment]
@katomel4 were you able to resolve this? Anything else we can help with?

**Comment by skriss** [comment]
Closing as inactive -- feel free to reach out again as needed.
