### ISSUE TITLE
support incremental snapshots of Azure disks

### ISSUE THREAD

**Issue by varuzam** [vmware-tanzu/velero-plugin-for-microsoft-azure#25]
https://azure.microsoft.com/ru-ru/blog/introducing-cost-effective-increment-snapshots-of-azure-managed-disks-in-preview/

**Comment by skriss** [comment]
It does not, no. Reading that article, it doesn't sound like the option is available yet via the Go SDK, so we may need to wait a little while before supporting it.

Do you want to leave this issue open as a feature request? If so, do you have any interest in working on it when it's ready?

**Comment by varuzam** [comment]
I would like to leave the issue as a feature request. Unfortunately, I am not a Go developer.

**Comment by rocketraman** [comment]
FYI, this feature is now GA in Azure. I created this issue for the Go SDK: https://github.com/Azure/azure-sdk-for-go/issues/8086.

**Comment by rocketraman** [comment]
Apparently version v41.0.0 of the Go SDK now has this feature. See https://github.com/Azure/azure-sdk-for-go/issues/8086#issuecomment-606545533.

**Comment by skriss** [comment]
cc @NickSu86

**Comment by NickSu86** [comment]
> cc @NickSu86

Thank you, how about AWS, does the aws plugin take snapshot incrementally by default? Thank you

**Comment by varuzam** [comment]
it does

**Comment by stephanwehr** [comment]
It would be great to have the option to use incremental snapshots.

**Comment by skriss** [comment]
:+1: if anyone's interested in working on a contribution here, let us know!

**Comment by stephanwehr** [comment]
added pr #52

**Comment by Juhibhadviya19** [comment]
@stephanwehr Works for me. Thanks a lot, it was much needed.
@skriss When can we expect its docker image to be published in velero repo?

**Comment by stephanwehr** [comment]
@Juhibhadviya19 Have you seen my last comment in the pr?

**Comment by Juhibhadviya19** [comment]
@stephanwehr  All the 3 test cases behaved as mentioned by you in https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/52#issuecomment-648704782
