### ISSUE TITLE
Azure blob storage backups larger than 256MiB fail due to RequestBodyTooLarge Error

### ISSUE THREAD

**Issue by dharmab** [vmware-tanzu/velero-plugin-for-microsoft-azure#26]
**What steps did you take and what happened:**

When running backups to Azure blob storage from a large cluster, the backup fails with the following error:

```
time="2020-02-25T22:08:02Z" level=error msg="backup failed" controller=backup error="rpc error: code = Unknown desc = storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.\nRequestId:9a1043dc-601e-005f-7828-ecd157000000\nTime:2020-02-25T22:08:02.6045264Z, RequestInitiated=Tue, 25 Feb 2020 22:08:02 GMT, RequestId=9a1043dc-601e-005f-7828-ecd157000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=" key=velero/hourly-k8s-backup-20200225220036 logSource="pkg/controller/backup_controller.go:233"
```

**What did you expect to happen:**

Backups should succeed

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

See above

**Anything else you would like to add:**

~~Apparently there is a 4MB chunk limit with Azure Blob Store, and chunking is required above 4MB: https://support.microsoft.com/en-us/help/4016806/the-request-body-is-too-large-error-when-writing-data-to-azure-file~~ This specific document was for Azure File and not Blob Store, see comment below

**Environment:**

- Velero version (use `velero version`): 1.1.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.16.7
- Kubernetes installer & version: custom
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): CoreOS Container Linux

**Comment by dharmab** [comment]
More information: https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks

> The maximum size for a block blob created via Put Blob is 256 MB for version 2016-05-31 and later, and 64 MB for older versions. If your blob is larger than 256 MB for version 2016-05-31 and later, or 64 MB for older versions, you must upload it as a set of blocks. For more information, see the Put Block and Put Block Listoperations. It's not necessary to also call Put Blob if you upload the blob as a set of blocks.
>
> If you attempt to upload a block blob that is larger than 256 MB for version 2016-05-31 and later, and 64 MB for older versions, or a page blob larger than 8 TB, the service returns status code 413 (Request Entity Too Large).

**Comment by dharmab** [comment]
Hmm:

https://github.com/Azure/azure-sdk-for-go/blob/cbb75bf1b53127c8f25a63b1d9e929d0d638246b/storage/blockblob.go#L99-L101

```
// The API rejects requests with size > 256 MiB (but this limit is not
// checked by the SDK). To write a larger blob, use CreateBlockBlob,
// PutBlock, and PutBlockList.
```

**Comment by dharmab** [comment]
So I guess this function:

https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/7a8cc9366f95fdb3aa30add3e60d0c7640edc99a/velero-plugin-for-microsoft-azure/object_store.go#L241-L248

should be changed to use CreateBlockBlob() to create a 0 byte blob, then read 256M chunks from the reader and call PutBlock repeatedly:

https://github.com/Azure/azure-sdk-for-go/blob/cbb75bf1b53127c8f25a63b1d9e929d0d638246b/storage/blockblob.go#L160-L169

**Comment by dharmab** [comment]
Here's a possible patch, however I feel like I'm in over my head and a project maintainer should consider taking over to do this correctly:

```
diff --git a/velero-plugin-for-microsoft-azure/object_store.go b/velero-plugin-for-microsoft-azure/object_store.go
index 8bfb6c9..59ed670 100644
--- a/velero-plugin-for-microsoft-azure/object_store.go
+++ b/velero-plugin-for-microsoft-azure/object_store.go
@@ -19,6 +19,7 @@ package main
 import (
 	"context"
 	"io"
+	"math"
 	"os"
 	"strings"
 	"time"
@@ -106,7 +107,38 @@ type azureBlob struct {
 }
 
 func (b *azureBlob) CreateBlockBlobFromReader(blob io.Reader, options *storage.PutBlobOptions) error {
-	return b.blob.CreateBlockBlobFromReader(blob, options)
+	// The Azure Storage API cannot accept blobs larger than 256MiB in a single
+	// request. Large blobs must be chunked as a series of 100MiB blocks.
+	buffer = make([]byte, 100*math.Pow(1024, 2))
+	chunkIndex = 0
+	putBlockListOptions := storage.PutBlockListOptions{
+		Timeout:   options.Timeout,
+		LeaseID:   options.LeaseID,
+		RequestId: options.RequestId,
+	}
+
+	for {
+		// https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#uri-parameters
+		blockID = fmt.Sprintf("%08d", chunkIndex)
+
+		chunk, readErr := blob.Read(buffer)
+		if readErr != nil {
+			if readErr != io.EOF {
+				return readErr
+			}
+		}
+
+		putErr := b.blob.PutBlock(blockID, chunk, PutBlobOptions)
+		if putErr != nil {
+			return putErro
+		}
+
+		if readErr == io.EOF {
+			return nil
+		}
+
+		chunkIndex++
+	}
 }
 
 func (b *azureBlob) Exists() (bool, error) {
```

This is probably the inefficient way to do it- There's a PutBlockList function in the Azure SDK that is probably better: https://github.com/Azure/azure-sdk-for-go/blob/cbb75bf1b53127c8f25a63b1d9e929d0d638246b/storage/blockblob.go#L252-L275

However my Go proficiency is pretty weak. I also don't know how to build the Velero plugin or run the tests.

**Comment by dharmab** [comment]
@skriss, I think the cause of the bug is well-understood. What else is needed for a bugfix?

**Comment by skriss** [comment]
@dharmab I'll see if I can spend some time on this today.

**Comment by skriss** [comment]
I made the code change (thanks @dharmab for the suggested patch, I used it as a ref but made a few modifications), now need to get an environment set up that I can test it in.
