### ISSUE TITLE
Azure plugin misleading documentation or not working 

### ISSUE THREAD

**Issue by lvadim01** [vmware-tanzu/velero-plugin-for-microsoft-azure#33]
**Error during deployment:**
`An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = config has invalid keys [storageAccountKeyEnvVar]; valid keys are [resourceGroup storageAccount subscriptionId bucket prefix]`

I am integrating Velero with Azure cluster following the documentation: 
[https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#Set-storage-account-access-key](url)

The approach used is:
**Set storage account access key** - for giving **azure  storage account permissions** to Velero without a SP.

` 1. AZURE_STORAGE_ACCOUNT_ACCESS_KEY=az storage account keys list --account-name $AZURE_STORAGE_ACCOUNT_ID --query "[?keyName == 'key1'].value" -o tsv`

`2. cat << EOF  > ./credentials-velero
    AZURE_STORAGE_ACCOUNT_ACCESS_KEY=${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
    AZURE_CLOUD_NAME=AzurePublicCloud
    EOF`

`3. velero install --provider azure --bucket $VELERO_BLOB_CONTAINER_NAME --secret-file ./credentials-velero --backup-location-config resourceGroup=$VELERO_RESOURCE_GROUP_NAME,storageAccount=$VELERO_STORAGE_ACCOUNT_NAME, storageAccountKeyEnvVar="AZURE_STORAGE_ACCOUNT_ACCESS_KEY"  --snapshot-location-config apiTimeout="5m",resourceGroup=$VELERO_RESOURCE_GROUP_NAME,subscriptionId=$SUBSCRIPTION_ID --plugins velero/velero-plugin-for-microsoft-azure:v1.0.0`

After deployment it does not recognize the ENV VAR from this documentation:
**storageAccountKeyEnvVar**:
```
    # Name of the environment variable in $AZURE_CREDENTIALS_FILE that contains storage account key for this backup storage location.
    #
    # Optional.
    storageAccountKeyEnvVar: MY_BACKUP_STORAGE_ACCOUNT_KEY
```

[https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/master/backupstoragelocation.md](url)

**Comment by skriss** [comment]
@lvadim01 this is a versioning issue - support for `storageAccountKeyEnvVar` was just recently added and is only available in the `master` image tag for the azure plugin, not the `v1.0.0` version that I see you're using from your `velero install` command. If you're comfortable using a CI build of the plugin, you can try out `master`, otherwise you'll need to wait until we do a new release of the plugin.

**Comment by lvadim01** [comment]
@skriss Thank you for the information!

**Comment by AkhilaDamera** [comment]
I am having similar issue with the `storageAccountKeyEnvVar:`

credentials-velero file:
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
AZURE_CLOUD_NAME=AzurePublicCloud

Command to install velero:
```
velero install \
--provider azure \
--plugins velero/velero-plugin-for-microsoft-azure:master \
--bucket $BLOB_CONTAINER \
--secret-file ./credentials-velero.yaml \
--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID,storageAccountKeyEnvVar='AZURE_STORAGE_ACCOUNT_ACCESS_KEY' \
--use-volume-snapshots=false \
--velero-pod-cpu-limit="0" --velero-pod-mem-limit="0" \
--velero-pod-mem-request="0" --velero-pod-cpu-request="0"
```
Error:
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = no storage account key found in env var AZURE_STORAGE_ACCOUNT_ACCESS_KEY

Velero client version: 1.4.2
Kubectl client - 1.15.0
kubectl server - 1.17.9
