### ISSUE TITLE
How to backup persistent volumes along with additional cluster resources and configurations

### ISSUE THREAD

**Issue by irniaxsep** [vmware-tanzu/velero-plugin-for-microsoft-azure#36]
I accidentally deleted persistence volume claim (PVC) attached in to one of our databases. But still I can see azure disk attached to the PVC exists in one of my resource groups. How can backup the data on the disk and copy to new disk.

**Comment by skriss** [comment]
@irniaxsep if the disk is no longer attached/exposed to your Kubernetes cluster through a PV/PVC, then Velero can't back it up. 

However, you could probably statically provision a new PV that makes use of your disk, and then use it via a new PVC.

**Comment by skriss** [comment]
See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#provisioning for some more information. You'd want to manually write the YAML for a new PV that uses your existing Azure disk.

I'm going to close this out as this isn't a Velero issue, but feel free to reach out again as needed. Thanks!
