### ISSUE TITLE
Node selector for linux

### ISSUE THREAD

**Issue by paulclark222** [vmware-tanzu/velero-plugin-for-microsoft-azure#42]
I have a cluster with windows and linux agent pools. After installing the velero pod is failing to start because it's running on a windows node. It needs a linux node selector.

**Comment by skriss** [comment]
It'd be great to add this to the documentation in this repo including instructions on how to edit the Velero deployment to add the node selector.

**Comment by Aboisier** [comment]
Here's a workaround: after installing velero, you can patch the deployment by using the following command:

```powershell
kubectl patch deploy velero --namespace velero --type merge --patch '{ \"spec\": { \"template\": { \"spec\": { \"nodeSelector\": { \"beta.kubernetes.io/os\": \"linux\"} } } } }'
```
