### ISSUE TITLE
Typos within the main page

### ISSUE THREAD

**Issue by Berndinox** [vmware-tanzu/velero-plugin-for-microsoft-azure#53]
there are alot of typos when following the guide, eg:

```
AZURE_CLIENT_SECRET=`az ad sp create-for-rbac --name "velero" --role "Contributor" --query 'password' -o tsv \
  --scopes  /subscriptions/$AZURE_SUBSCRIPTION_ID[ /subscriptions/$AZURE_BACKUP_SUBSCRIPTION_ID]`
```
should be
```
export AZURE_CLIENT_SECRET=`az ad sp create-for-rbac --name "velero" --role "Contributor" --query 'password' -o tsv \
  --scopes  /subscriptions/$AZURE_SUBSCRIPTION_ID /subscriptions/$AZURE_BACKUP_SUBSCRIPTION_ID`
```

**Comment by wjun** [comment]
Another one is : 
--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \

should be:
--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \

**Comment by wjun** [comment]
@ashish-amarnath I tried and it looks I am not in the vmware-tanzu organization so I cannot generate PRs?

**Comment by stephanwehr** [comment]
If I am not mistaken, the square bracket notation indicates, that everything in between is optional.

Are you sure those are typos?

**Comment by ashish-amarnath** [comment]
I thought that there were typos in how the document refers to these variables.

I am closing this issue and #65 
Please reach out if you need further assistance.
