### ISSUE TITLE
HELM Install Failing on Credential File

### ISSUE THREAD

**Issue by JClevengerGeico** [vmware-tanzu/velero-plugin-for-microsoft-azure#54]
Hello,

We are currently testing this plugin of Velero using HELM, and are running into an issue after installing:

Velero Version - 1.4.0
Chart Version - 2.12.0
Plugin Version - 1.2.0
Kubernetes - 1.15.7

```
time="2020-06-23T13:48:50Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_
ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID
```

Here is what our Credential-Velero file looks like:

```
AZURE_SUBSCRIPTION_ID=$(Plain Text String)
AZURE_TENANT_ID=$(Plain Text String)
AZURE_CLIENT_ID=$(Plain Text String)
AZURE_CLIENT_SECRET=$(Plain Text String)
AZURE_RESOURCE_GROUP=$(Plain Text String)
AZURE_CLOUD_NAME=AzurePublicCloud
```

Here is the command we are running (Being ran in PowerShell):

```
helm upgrade "$daemonsetName" "$chartFile" -f "$valuesFile" -n $daemonsetNamespace   `
--set-file credentials.secretContents.cloud=$credentialFile `
--set configuration.backupStorageLocation.config.resourceGroup=$resourceGroupName `
--set configuration.backupStorageLocation.config.storageAccount=$storageAccountName `
--set image.repository=$veleroImage `
--set initContainers[0].name="velero-plugin-for-microsoft-azure" `
--set initContainers[0].image=$pluginImage `
--set initContainers[0].volumeMounts[0].mountPath=/target `
--set initContainers[0].volumeMounts[0].name=plugins `
--install
```

The Credential-Velero file is located in the same folder as the chart

**Comment by nrb** [comment]
Apologies for the long delay in answering.

We've had some fixes go in for the Helm chart related to the Azure credentials.

Can you try upgrading to 2.12.13 and see if that takes care of it?

**Comment by jenting** [comment]
@JClevengerGeico iirc, the recently helm chart fixed this issue, could you please update the helm chart and make a try again? Thanks.

**Comment by jenting** [comment]
> @JClevengerGeico iirc, the recently helm chart fixed this issue, could you please update the helm chart and make a try again? Thanks.

@JClevengerGeico ping

**Comment by ashish-amarnath** [comment]
@JClevengerGeico Based on @jenting's comment this should be fixed. I am closing this issue, but please try this out with the latest version of the helm chart and reach out if you are still having issues.
