### ISSUE TITLE
Backup failed: plugin process exited, error="signal: killed" 

### ISSUE THREAD

**Issue by hammady** [vmware-tanzu/velero-plugin-for-microsoft-azure#63]
I installed velero 1.4.2 and the azure plugin 1.1.0 using the following:
```
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.1.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID \
    --snapshot-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP
```
All variables above have valid values, and the credentials file exists. Creating any backup fails with the following in the velero logs:
```
│ velero time="2020-08-18T10:42:41Z" level=debug msg="plugin process exited" backup=velero/pgtest cmd=/plugins/velero-plugin-for-microsoft-azure error="signal: killed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/plugins/velero-plugin-for-microsoft-azure pid=77                                                     │
│ velero time="2020-08-18T10:42:41Z" level=error msg="backup failed" controller=backup error="[rpc error: code = Unknown desc = EOF, rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin872831740: connect: connection refused\"]" key=velero/pgtest logSource="pkg/con │
│ troller/backup_controller.go:273"
```
When I check on the Azure portal, I can see the snapshot taken but only the `logs.gz` object stored on the blob. Sometimes I see other objects (but others are missing):
```
[..]
pgtest-logs.gz
pgtest-podvolumebackups.json.gz
pgtest-volumesnapshots.json.gz
```
This means that velero can connect normally to Azure, but for some reason the plugin code gets killed causing the backup operation to fail. Is this a known issue?
The backup is simply for a namespace with postgres installed with no data that I installed using:
```
helm install pgtest bitnami/postgresql  
``` 
The last line in the backup logs looks normal:
```
time="2020-08-18T10:42:11Z" level=info msg="Backed up a total of 13 items" backup=velero/pgtest logSource="pkg/backup/backup.go:436" progress=
```
This means velero has finished backing up everything and even snapshotting the volume, but it crashes during the upload process of the backup archive to Azure.

**Comment by hammady** [comment]
Tried the same setup with velero 1.3.2 and azure plugin 1.0.1 and it worked perfectly! Seems like a bug in the plugin version 1.1.

**Comment by ashish-amarnath** [comment]
@hammady Can you please try to increase memory limits for Velero and try again?

**Comment by ashish-amarnath** [comment]
This is most likely related to https://github.com/vmware-tanzu/velero/issues/1856

**Comment by ashish-amarnath** [comment]
I am going to close this issue. Please re-open or reach out if you have more questions.
