### ISSUE TITLE
Support for Velero version 1.5.x

### ISSUE THREAD

**Issue by SatyKrish** [vmware-tanzu/velero-plugin-for-microsoft-azure#73]
Compatibility matrix show `plugin version 1.1.x` supports `velero version 1.4.x`.

Are there plans to add support for `velero 1.5.x `version?

**Comment by jenting** [comment]
#76 merged, this issue could be closed.

**Comment by ashish-amarnath** [comment]
As @jenting points out, the compatibility matrix of the plugin is now updated.
Closing this issue.
