### ISSUE TITLE
Azure plugin PV backup issue with AAD identity 

### ISSUE THREAD

**Issue by Abhiger** [vmware-tanzu/velero-plugin-for-microsoft-azure#74]
Hi guys,
I am struggling with PVs backup on Azure with the usage of velero-plugin-for-microsoft-azure.

Get the below error .Although i've specified the values correctly for Subscription and resourcegroup
 msg="Error getting volume snapshotter for volume snapshot location" backup=velero/test-backup2 error="rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/volume_snapshotter.go:96" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:448" name=pvc-79cf5f14-64ea-461b-849f-f02724c2fbde namespace= persistentVolume=pvc-79cf5f14-64ea-461b-849f-f02724c2fbde resource=persistentvolumes volumeSnapshotLocation=default

I'm using  velero-plugin-for-microsoft-azure:main as per suggestion on the issue related to AAD POD Identity [unable to use AAD Pod Identity] (https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/issues/61) 

Backup fails with above error if PV is involved . Non-pv backups work as expected

**Comment by aristosvo** [comment]
Looks like your setup is not complete, as it needs a cloud-credentials secret which contains AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP. How did you configure your setup?

**Comment by Abhiger** [comment]
I'm installing using Helm for AAD Pod identity . I'm creating the  file with relevant environment variables  as per the [documentation](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure)

CAT << EOF  > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzurePublicCloud
EOF

I'm passing the above file which contains Azure Provider information  to helm  using the --set-file argument 

  helm upgrade velero vmware-tanzu/velero \
        --namespace velero \
        --values ./velero-config.yml \
        --version 2.13.3  \ 
        --set-file credentials.secretContents.cloud=./credentials-velero \
        --install \
        --atomic \
        --cleanup-on-fail \
        --reuse-values \
        --debug

The above installs velero successfully . However i get the below error  and the backup ends in **PartiallyFailed** state . I'm passing all the requisite values in Helm config for AKS

"Error getting volume snapshotter for volume snapshot location" backup=velero/velero-dailybackup-20201020110744 error="rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/volume_snapshotter.go:96" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:449" name=pvc-xxx namespace= persistentVolume=pvc-xxxx resource=persistentvolumes volumeSnapshotLocation=default"


Let me know if you need additional information



> Looks like your setup is not complete, as it needs a cloud-credentials secret which contains AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP. How did you configure your setup?

**Comment by Abhiger** [comment]
Another thing i observed is Immediately after the error i get the following in the logs 
level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/velero-dailybackup-20201020110744 logSource="pkg/backup/item_backupper.go:469" name=pvc-503332e9-7ded-4147-9238-4b8c550f46f4 namespace= persistentVolume=pvc-503332e9-7ded-4147-9238-4b8c550f46f4 resource=persistentvolumes

**Comment by Abhiger** [comment]
I'm including the values file that i'm passing to helm charts

> I'm installing using Helm for AAD Pod identity . I'm creating the file with relevant environment variables as per the [documentation](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure)
> 
> CAT << EOF > ./credentials-velero
> AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
> AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
> AZURE_CLOUD_NAME=AzurePublicCloud
> EOF
> 
> I'm passing the above file which contains Azure Provider information to helm using the --set-file argument
> 
> helm upgrade velero vmware-tanzu/velero
> --namespace velero
> --values ./velero-config.yml
> --version 2.13.3 \
> --set-file credentials.secretContents.cloud=./credentials-velero
> --install
> --atomic
> --cleanup-on-fail
> --reuse-values
> --debug
> 
> The above installs velero successfully . However i get the below error and the backup ends in **PartiallyFailed** state . I'm passing all the requisite values in Helm config for AKS
> 
> "Error getting volume snapshotter for volume snapshot location" backup=velero/velero-dailybackup-20201020110744 error="rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/volume_snapshotter.go:96" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:449" name=pvc-xxx namespace= persistentVolume=pvc-xxxx resource=persistentvolumes volumeSnapshotLocation=default"
> 
> Let me know if you need additional information
> 
> > Looks like your setup is not complete, as it needs a cloud-credentials secret which contains AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP. How did you configure your setup?

#

**Comment by ashish-amarnath** [comment]
@Abhiger To troubleshoot the below error:
> msg="Error getting volume snapshotter for volume snapshot location" backup=velero/test-backup2 error="rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/volume_snapshotter.go:96" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:448" name=pvc-79cf5f14-64ea-461b-849f-f02724c2fbde namespace= persistentVolume=pvc-79cf5f14-64ea-461b-849f-f02724c2fbde resource=persistentvolumes volumeSnapshotLocation=default

Can you please do the following?
1. Confirm that the credentials file `credentials-velero` that you are using in the helm configuration has all the necessary config fields per the documentation at https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-2-use-aad-pod-identity
2. Inspect the `cloud-credentials` secret exists in the velero namespace and that it's contents match with the contents of your `credentials-velero` file.
`kubectl -n velero get secrets cloud-credentials -ojson | jq .data.cloud -r | base64 --decode`

**Comment by Abhiger** [comment]
Hi @ashish-amarnath  the credential **exactly match the contents of credentials-velero file** 

AZURE_SUBSCRIPTION_ID=<subscriptionID >
AZURE_RESOURCE_GROUP=<aks auto generated RG>
AZURE_CLOUD_NAME=AzurePublicCloud

I remember reading on some posts that credentials file before passing it to the helm chart all occurrences of  "\r\n" should be replaced with "\n" .. do we need to take care of that step

**Comment by ashish-amarnath** [comment]
@Abhiger Can you try that suggestion of replacing the control characters?
If that doesn't work, then we can take helm out of the picture for now and try installing using `velero install`

```
velero install \
        --provider azure \
        --plugins ${VELERO_PLUGINS} \
        --bucket $BLOB_CONTAINER \
        --secret-file <CREDENTIALS_FILE> \
        --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
        --image ${VELERO_IMAGE}
```

If that works then we can troubleshoot helm.

**Comment by Abhiger** [comment]
@ashish-amarnath the issue got resolved after replacing the control characters 😊

**Comment by ashish-amarnath** [comment]
Thank you for confirming! Going to close this issue as resolved.
