### ISSUE TITLE
Backups fail with RPC error: transport is closing

### ISSUE THREAD

**Issue by ashwin-venkatesh** [vmware-tanzu/velero-plugin-for-microsoft-azure#77]
Hey y'all,

Been trying to setup Velero with the 1.1.1 azure plugin to backup resources from my cluster. They backup appears to run successfully and there are no issues in the logs describing the backup job. 
In the controller logs I see the following error:
`level=error msg="backup failed" controller=backup error="rpc error: code = Unavailable desc = transport is closing" key=velero/complete logSource="pkg/controller/backup_controller.go:279"`

When I look at the blob bucket where I expect the backup, the only file is a log file `complete-log.gz`. Those logs itself have no error on them. Let me know what other information I can provide to help with the debugging.

If it helps, I was able to successfully backup my cluster once yesterday using the same azure config, but all subsequent backups have failed with the above RPC error. Trying to restore from this fialed backup leads to a file not found error.

**Comment by ashish-amarnath** [comment]
@ashwin-venkatesh can you please try this again with increased resource limits on the `velero` deployment?
Instructions on how to do that is available on our docs website at https://velero.io/docs/v1.5/customize-installation/#customize-resource-requests-and-limits

**Comment by ashwin-venkatesh** [comment]
Oh sweet!! That worked. Thanks @ashish-amarnath 

Would you happen to have a rubric or guideline regarding what reasonable requests and limits for the deployment should be? Is it just azure that needs its values bumped? I only ask because I might have to make a `velero` recommendation and it would help to know what would be the ideal config in different use-cases. 

Does it depend on the "volume" of the workloads it is backing up? Additionally, it would be neat if the logs could potentially indicate that it was a resource limit issue though I do see how that could be a little tricky to determine.

Really appreciate the help though bud!!

**Comment by ashish-amarnath** [comment]
@ashwin-venkatesh Yes, it is just the azure plugin that requires this customization. Everything else should be able to run with defaults.
The resource limits don't depend on the volume of workloads,
I agree that the error could be better. But when this happens the velero pod is OOM killed so we'll not be able to log messages to that effect.

No problem. I am going to close this issue as resolved.

**Comment by Zeka13** [comment]
faced the same problem, how about to increase default values? Confused for new users who just installed Velero on Azure
