### ISSUE TITLE
Azure Storage Resource Provider rate limits may cause backup failures

### ISSUE THREAD

**Issue by dharmab** [vmware-tanzu/velero-plugin-for-microsoft-azure#80]
This issue is not a bug with Velero or the plugin, IMO. It is a "gotcha" with how Velero uses the Microsoft Azure APIs. I'm opening a git issue to make this problem easy to find in Google search results.

If you use the Service Principal or Managed Identity authentication methods for the Velero plugin, and the Storage Account you use for your backups is shared with multiple instances of Velero, then it is possible to encounter rate limits for the Storage Resource Provider (SRP) within Azure:

```
# Status: 429
# content-length: 226
# content-type: application/json
# date: Thu, 29 Oct 2020 16:39:56 GMT
# expires: -1
# instance-name: explorer-bay
# retry-after: 17
# strict-transport-security: max-age=31536000; includeSubDomains
# x-content-type-options: nosniff
# x-ms-ellapsed: 160ms
# x-ms-ratelimit-remaining-subscription-reads: 11998
{
  "error": {
    "code": "TooManyRequests",
    "message": "The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits"
  }
}
```

Note that the [SRP rate limit](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#storage-throttling) is different from the [ARM API rate limit](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#subscription-and-tenant-limits). The SRP limits are significantly lower. Through experimental verification, we confirmed that the SRP rate limit is scoped to the Azure Subscription of the Storage Account.

This error causes Velero to log the following errors before crashing:

```
time="2020-10-28T22:07:30Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\"TooManyRequests\" Message=\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\"" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:205" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:168"
time="2020-10-28T22:07:30Z" level=error msg="Error getting a backup store" backupstoragelocation=default controller=backupstoragelocation error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\"TooManyRequests\" Message=\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\"" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:205" error.function=main.getStorageAccountKey logSource="pkg/controller/backupstoragelocation_controller.go:82
```

Unfortunately, the Kubernetes PodCrashLoopBackOff and the SRP rate limit time window are both 5 minutes. This causes Velero's retry to align with the rate limit, preventing any effective backoff.

We saw these limits when we had around 100 clusters backing up to the same storage account. The limits could possibly be encountered at a lower threshold if Velero shares a storage account with other software. 

Solutions:

- If you are only backing up Kubernetes Resources and not any Persistent Volumes, you can authenticate Velero using a Storage Access Key instead of a Service Principal. This removes the necessity of any ARM API calls to the SRP.
- You can spread your Velero instances' backups across multiple Azure Subscriptions.
- You can send your Velero backups to another cloud provider which has higher rate limits.

I'd be happy to contribute a doc for this- should I add a section to README.md, or somewhere else?

**Comment by ashish-amarnath** [comment]
@dharmab It is possible to reduce the frequency of `BackupStorageLocation`'s availability check using the [`ValidationFrequency `](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/backupstoragelocation_types.go#L47) field of the `BackupStorageLocationSpec`.
Setting this to 0 will disable repeated validation of the BackupStorageLocation. All BSLs should be validated at least once but I found a bug that prevents that from happening and it is fixed in https://github.com/vmware-tanzu/velero/pull/3084.
So my recommendation is setting a large value for this field, say `1h`. This should remedy the issue.

**Comment by ashish-amarnath** [comment]
Considering that there is a way to disable the repeated validations, I am going to close this issue. Please reach out if you have more questions.
